apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-library
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/plex"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-library
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
